model_provider="openrouter"
model="gpt-5.1-codex-max"
model_reasoning_effort = "medium"
personality = "pragmatic"

[model_providers.openrouter]
name="openrouter"
base_url="https://openrouter.ai/api/v1"
env_key="OPENROUTER_API_KEY"
